COLUMNS = ['activity_type',
           'duration',
           'duration_unit',
           'total_distance',
           'total_distance_unit',
           'total_energy_burned',
           'total_energy_burned_unit',
           'device',
           'creation_date',
           'start_date',
           'end_date',
           'route',
           'metadata_dict']

FLOAT_COLUMNS = ['duration', 
                 'total_distance', 
                 'total_energy_burned', 
                 'average_mets', 
                 'temperature', 
                 'humidity', 
                 'elevation_ascended']

DATETIMESTAMP_COLUMNS = ['creation_date', 
                         'start_date', 
                         'end_date']

FORMATTED_COLUMNS = ['activity_type',
                     'duration',
                     'duration_unit',
                     'total_distance',
                     'total_distance_unit',
                     'total_energy_burned',
                     'total_energy_burned_unit',
                     'was_indoor_workout',
                     'average_mets',
                     'average_mets_unit',
                     'temperature',
                     'temperature_unit',
                     'humidity',
                     'humidity_unit',
                     'elevation_ascended',
                     'elevation_ascended_unit',
                     'device',
                     'creation_date',
                     'start_date',
                     'end_date',
                     'timezone',
                     'route',
                     'metadata_dict']

